let allGroups = [
    {
        id: 0,
        name: ["Solo"],
        size: 1,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 1,
        name: ["Weeekly"],
        size: 6,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 2,
        name: ["Blackpink"],
        size: 4,
        fandom: ["Blink"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 3,
        name: ["Itzy"],
        size: 5,
        fandom: ["Midzy"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 4,
        name: ["Mamamoo", "MMM"],
        size: 4,
        fandom: ["Moomoo"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 5,
        name: ["Aespa"],
        size: 4,
        fandom: ["My"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 6,
        name: ["NMIXX"],
        size: 6,
        fandom: ["NSWER"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 7,
        name: ["Viviz"],
        size: 3,
        fandom: ["Na.V", "NaV"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 8,
        name: ["Kep1er"],
        size: 9,
        fandom: ["Kep1ian"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 9,
        name: ["(G)I-DLE", "GIDLE"],
        size: 5,
        fandom: ["Neverland"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 10,
        name: ["Red Velvet", "RedVelvet", "RV"],
        size: 5,
        fandom: ["Neverland"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 11,
        name: ["Le Sserafim", "LeSserafim"],
        size: 5,
        fandom: ["Fearnot"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 12,
        name: ["IVE"],
        size: 6,
        fandom: ["Dive"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 13,
        name: ["Twice"],
        size: 9,
        fandom: ["Once"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 14,
        name: ["Loona"],
        size: 12,
        fandom: ["Orbit"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 15,
        name: ["Artms"],
        size: 5,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 16,
        name: ["Loossemble"],
        size: 5,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 17,
        name: ["StayC"],
        size: 6,
        fandom: ["Swith"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 18,
        name: ["Momoland"],
        size: 6,
        fandom: ["Merry-Go-Round", "MerryGoRound"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 19,
        name: ["Cignature"],
        size: 8,
        fandom: ["Signfan"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 20,
        name: ["Dreamcatcher"],
        size: 7,
        fandom: ["Insomnia"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 21,
        name: ["Everglow"],
        size: 6,
        fandom: ["Forever"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 22,
        name: ["Purple Kiss", "PurpleKiss"],
        size: 6,
        fandom: ["Plory"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 23,
        name: ["BVNDIT"],
        size: 5,
        fandom: ["Bvnditbul"],
        debut: new Date("2019-04-10"),
        disband: new Date("2022-10-31"),
    },
    {
        id: 24,
        name: ["Stray Kids", "StrayKids"],
        size: 8,
        fandom: ["Stay"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 25,
        name: ["Exo"],
        size: 8,
        fandom: ["EXO-L"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 26,
        name: ["Rolling Quartz", "RollingQuartz"],
        size: 5,
        fandom: ["Diadem"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 27,
        name: ["Cherry Bullet", "CherryBullet"],
        size: 7,
        fandom: ["Lullet"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 28,
        name: ["Lightsum"],
        size: 6,
        fandom: ["Sumit"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 29,
        name: ["Monsta X", "MonstaX"],
        size: 6,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 30,
        name: ["Ab6ix"],
        size: 4,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 31,
        name: ["Enhypen"],
        size: 6,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 32,
        name: ["Oneus"],
        size: 5,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 33,
        name: ["NCT"],
        size: 20,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 34,
        name: ["BTS"],
        size: 7,
        fandom: ["Army"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 35,
        name: ["Super Junior", "SuperJunior"],
        size: 10,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 36,
        name: ["Billlie"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 37,
        name: ["A.C.E", "ACE"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 38,
        name: ["Ateez"],
        size: 0,
        fandom: ["Atiny"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 39,
        name: ["Astro"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 40,
        name: ["Treasure"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 41,
        name: ["CLASS:y", "CLASSy"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 42,
        name: ["geenius"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 43,
        name: ["iii"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 44,
        name: ["ICHILLIN"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 45,
        name: ["Oh My Girl", "OhMyGirl", "OMG"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 46,
        name: ["Kard"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 47,
        name: ["BB Girls", "BBGirls"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 48,
        name: ["WOO!AH!", "WOOAH"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 49,
        name: ["Craxy"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 50,
        name: ["Pixy"],
        size: 5,
        fandom: ["Winxy"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 51,
        name: ["Busters"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 52,
        name: ["WJSN"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 53,
        name: ["NewJeans"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 54,
        name: ["Gugudan"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 55,
        name: ["tripleS"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 56,
        name: ["Pentagon"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 57,
        name: ["Cravity"],
        size: 0,
        fandom: ["Luvity"],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 58,
        name: ["ADYA"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 59,
        name: ["Babymonster"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 60,
        name: ["XG"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 61,
        name: ["Lapillus"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 62,
        name: ["Seventeen"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 63,
        name: ["Rocket Punch", "RocketPunch"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 64,
        name: ["Weki Meki", "WekiMeki"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 65,
        name: ["AOA"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 66,
        name: ["TRI.BE", "TRIBE"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 67,
        name: ["fromis_9", "fromis9", "fromis_9"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 68,
        name: ["SNSD"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 69,
        name: ["Apink"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 70,
        name: ["Kiss of Life", "KissOfLife", "Kiof", "kol"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 71,
        name: ["MCND"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 72,
        name: ["Young Posse", "YoungPosse"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 73,
        name: ["iScream"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 74,
        name: ["8Turn"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 75,
        name: ["Shinee"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 76,
        name: ["April"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 77,
        name: ["ANS"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 78,
        name: ["CLC"],
        size: 0,
        fandom: [""],
        debut: new Date(""),
        disband: new Date(""),
    },
    {
        id: 79,
        name: ["Iz*One", "IzOne"],
        size: 12,
        fandom: ["Wiz*One"],
        debut: new Date(""),
        disband: new Date(""),
    },

    
]

let allMembers = [

    //Solos
    {
        name: ["JYP - Leader of Disappointment", "JYP"],
        group: [0],
        birthday: new Date("1971-12-13"),
    },
    {
        name: ["PSY"],
        group: [0],
        birthday: new Date("1977-12-31"),
    },
    {
        name: ["Chungha"],
        group: [0],
        birthday: new Date("1996-02-09"),
    },
    {
        name: ["Soyou"],
        group: [0],
        birthday: new Date("1992-02-12"),
    },
    {
        name: ["Hyolyn"],
        group: [0],
        birthday: new Date("1990-12-11"),
    },
    {
        name: ["Somi"],
        group: [0],
        birthday: new Date("2001-03-09"),
    },
    {
        name: ["BabySoul"],
        group: [0],
        birthday: new Date("1992-07-06"),
    },
    {
        name: ["Suzy"],
        group: [0],
        birthday: new Date("1994-10-10"),
    },
    {
        name: ["Taeyeon"],
        group: [0],
        birthday: new Date("1989-03-09"),
    },
    {
        name: ["Hyuna"],
        group: [0],
        birthday: new Date("1992-06-06"),
    },
    {
        name: ["Sunmi"],
        group: [0],
        birthday: new Date("1992-05-02"),
    },
    {
        name: ["IU"],
        group: [0],
        birthday: new Date("1993-05-16"),
    },
    {
        name: ["G-Dragon", "GDragon"],
        group: [0],
        birthday: new Date("1988-08-18"),
    },
    {
        name: ["Bibi"],
        group: [0],
        birthday: new Date("1998-09-27"),
    },
    {
        name: ["Young-Ji", "YoungJi"],
        group: [0],
        birthday: new Date("2002-09-10"),
    },
    {
        name: ["Alexa"],
        group: [0],
        birthday: new Date("1996-12-09"),
    },
    {
        name: ["Boa"],
        group: [0],
        birthday: new Date("1986-11-05"),
    },
    {
        name: ["Holland"],
        group: [0],
        birthday: new Date("1996-03-04"),
    },

    //Gruppen
    {
        name: ["Jiyoon"],
        group: [-1],
        birthday: new Date("2002-03-02"),
    },
    {
        name: ["Jaehee"],
        group: [1],
        birthday: new Date("2004-03-18"),
        },
    {
        name: ["Monday"],
        group: [1],
        birthday: new Date("2002-05-10"),
    },
    {
        name: ["Zoa"],
        group: [1],
        birthday: new Date("2005-05-31"),
    },
    {
        name: ["Jihan"],
        group: [1],
        birthday: new Date("2004-07-12"),
    },
    {
        name: ["Soeun"],
        group: [1],
        birthday: new Date("2002-10-26"),
    },
    {
        name: ["Soojin"],
        group: [1],
        birthday: new Date("2001-12-12"),
    },
    {
        name: ["Jisoo"],
        group: [2],
        birthday: new Date("1995-01-03"),
    },
    {
        name: ["Jennie"],
        group: [2],
        birthday: new Date("1996-01-16"),
    },
    {
        name: ["Rose"],
        group: [2],
        birthday: new Date("1997-02-11"),
    },
    {
        name: ["Lisa"],
        group: [2],
        birthday: new Date("1997-03-27"),
    },
    {
        name: ["Ryujin"],
        group: [3],
        birthday: new Date("2001-04-17"),
    },
    {
        name: ["Yeji"],
        group: [3],
        birthday: new Date("2000-05-26"),
    },
    {
        name: ["Chaeryeong"],
        group: [3],
        birthday: new Date("2001-06-05"),
    },
    {
        name: ["Lia"],
        group: [3],
        birthday: new Date("2000-07-21"),
    },
    {
        name: ["Yuna"],
        group: [3],
        birthday: new Date("2003-12-09"),
    },
    {
        name: ["Solar"],
        group: [4],
        birthday: new Date("1991-02-21"),
    },
    {
        name: ["Wheein"],
        group: [4],
        birthday: new Date("1995-04-17"),
    },
    {
        name: ["Hwasa"],
        group: [4],
        birthday: new Date("1995-07-23"),
    },
    {
        name: ["Moonbyul"],
        group: [4],
        birthday: new Date("1992-12-22"),
    },
    {
        name: ["Winter"],
        group: [5],
        birthday: new Date("2001-01-01"),
    },
    {
        name: ["Karina"],
        group: [5],
        birthday: new Date("2000-04-11"),
    },
    {
        name: ["NingNing"],
        group: [5],
        birthday: new Date("2002-10-23"),
    },
    {
        name: ["Giselle"],
        group: [5],
        birthday: new Date("2000-10-30"),
    },
    {
        name: ["Sullyoon"],
        group: [6],
        birthday: new Date("2004-01-26"),
    },
    {
        name: ["Haewon"],
        group: [6],
        birthday: new Date("2003-02-25"),
    },
    {
        name: ["Jiwoo"],
        group: [6],
        birthday: new Date("2005-04-13"),
    },
    {
        name: ["Jinni"],
        group: [-6],
        birthday: new Date("2004-04-16"),
    },
    {
        name: ["Kyujin"],
        group: [6],
        birthday: new Date("2006-05-26"),
    },
    {
        name: ["Lily"],
        group: [6],
        birthday: new Date("2002-10-17"),
    },
    {
        name: ["Bae"],
        group: [6],
        birthday: new Date("2004-12-28"),
    },
    {
        name: ["Eunha"],
        group: [7],
        birthday: new Date("1997-05-30"),
    },
    {
        name: ["SinB"],
        group: [7],
        birthday: new Date("1998-06-03"),
    },
    {
        name: ["Umji"],
        group: [7],
        birthday: new Date("1998-08-19"),
    },
    {
        name: ["Dayeon"],
        group: [8],
        birthday: new Date("2003-03-02"),
    },
    {
        name: ["Hikaru"],
        group: [8],
        birthday: new Date("2004-03-12"),
    },
    {
        name: ["Chaehyun"],
        group: [8],
        birthday: new Date("2002-04-26"),
    },
    {
        name: ["Bahiyyih"],
        group: [8],
        birthday: new Date("2004-07-27"),
    },
    {
        name: ["Yujin"],
        group: [8],
        birthday: new Date("1996-08-12"),
    },
    {
        name: ["Yeseo"],
        group: [8],
        birthday: new Date("2005-08-22"),
    },
    {
        name: ["Xiaoting", "XT"],
        group: [8],
        birthday: new Date("1999-11-12"),
    },
    {
        name: ["Mashiro"],
        group: [8],
        birthday: new Date("1999-12-16"),
    },
    {
        name: ["Youngeun"],
        group: [8],
        birthday: new Date("2004-12-27"),
    },
    {
        name: ["Shuhua"],
        group: [9],
        birthday: new Date("2000-01-06"),
    },
    {
        name: ["Miyeon"],
        group: [9],
        birthday: new Date("1997-01-31"),
    },
    {
        name: ["Soojin"],
        group: [-9],
        birthday: new Date("1998-03-09"),
    },
    {
        name: ["Soyeon"],
        group: [9],
        birthday: new Date("1998-08-26"),
    },
    {
        name: ["Yuqi"],
        group: [9],
        birthday: new Date("1999-09-23"),
    },
    {
        name: ["Minnie"],
        group: [9],
        birthday: new Date("1997-10-23"),
    },
    {
        name: ["Seulgi"],
        group: [10],
        birthday: new Date("1994-02-10"),
    },
    {
        name: ["Wendy"],
        group: [10],
        birthday: new Date("1994-02-21"),
    },
    {
        name: ["Yeri"],
        group: [10],
        birthday: new Date("1999-03-05"),
    },
    {
        name: ["Irene"],
        group: [10],
        birthday: new Date("1991-03-29"),
    },
    {
        name: ["Joy"],
        group: [10],
        birthday: new Date("1996-09-03"),
    },
    {
        name: ["Kazuha"],
        group: [11],
        birthday: new Date("2003-08-09"),
    },
    {
        name: ["Yunjin"],
        group: [11],
        birthday: new Date("2001-10-08"),
    },
    {
        name: ["Eunchae"],
        group: [11],
        birthday: new Date("2006-11-10"),
    },
    {
        name: ["Garam"],
        group: [-11],
        birthday: new Date("2005-11-16"),
    },
    {
        name: ["Sakura"],
        group: [11, 79],
        birthday: new Date("1998-03-19"),
    },
    {
        name: ["Chaewon"],
        group: [11, 79],
        birthday: new Date("2000-08-01"),
    },
    {
        name: ["Chaeyeon"],
        group: [79],
        birthday: new Date("2000-01-11"),
    },
    {
        name: ["Minju"],
        group: [79],
        birthday: new Date("2001-02-05"),
    },
    {
        name: ["Nako"],
        group: [79],
        birthday: new Date("2001-06-18"),
    },
    {
        name: ["Hyewon"],
        group: [79],
        birthday: new Date("1999-07-05"),
    },
    {
        name: ["Eunbi"],
        group: [79],
        birthday: new Date("1995-09-27"),
    },
    {
        name: ["Yena"],
        group: [79],
        birthday: new Date("1999-09-29"),
    },
    {
        name: ["Hitomi"],
        group: [79],
        birthday: new Date("2001-10-06"),
    },
    {
        name: ["Yuri"],
        group: [79],
        birthday: new Date("2001-10-22"),
    },
    {
        name: ["Wonyoung"],
        group: [12, 79],
        birthday: new Date("2004-08-31"),
    },
    {
        name: ["Yujin"],
        group: [12, 79],
        birthday: new Date("2003-09-01"),
    },
    {
        name: ["Rei"],
        group: [12],
        birthday: new Date("2004-02-03"),
    },
    {
        name: ["Leeseo"],
        group: [12],
        birthday: new Date("2007-02-21"),
    },
    {
        name: ["Gaeul"],
        group: [12],
        birthday: new Date("2002-09-24"),
    },
    {
        name: ["Liz"],
        group: [12],
        birthday: new Date("2004-11-21"),
    },
    {
        name: ["Jihyo"],
        group: [13],
        birthday: new Date("1997-02-01"),
    },
    {
        name: ["Mina"],
        group: [13],
        birthday: new Date("1997-03-24"),
    },
    {
        name: ["Chaeyoung"],
        group: [13],
        birthday: new Date("1999-04-23"),
    },
    {
        name: ["Dahyun"],
        group: [13],
        birthday: new Date("1998-05-28"),
    },
    {
        name: ["Tzuyu"],
        group: [13],
        birthday: new Date("1999-06-14"),
    },
    {
        name: ["Nayeon"],
        group: [13],
        birthday: new Date("1995-09-22"),
    },
    {
        name: ["Jeongyeon"],
        group: [13],
        birthday: new Date("1996-11-01"),
    },
    {
        name: ["Momo"],
        group: [13],
        birthday: new Date("1996-11-09"),
    },
    {
        name: ["Sana"],
        group: [13],
        birthday: new Date("1996-12-29"),
    },
    {
        name: ["Kim Lip", "KimLip"],
        group: [15, 14],
        birthday: new Date("1999-02-10"),
    },
    {
        name: ["Yves"],
        group: [14],
        birthday: new Date("1997-05-24"),
    },
    {
        name: ["Choerry"],
        group: [15, 14],
        birthday: new Date("2001-06-04"),
    },
    {
        name: ["Jinsoul"],
        group: [15, 14],
        birthday: new Date("1997-06-13"),
    },
    {
        name: ["Haseul"],
        group: [15, 14],
        birthday: new Date("1997-08-18"),
    },
    {
        name: ["Heejin"],
        group: [15, 14],
        birthday: new Date("2000-10-19"),
    },
    {
        name: ["Chuu"],
        group: [-14],
        birthday: new Date("1999-10-20"),
    },
    {
        name: ["Yeojin"],
        group: [16, 14],
        birthday: new Date("2002-11-11"),
    },
    {
        name: ["Hyejoo"],
        group: [16, 14],
        birthday: new Date("2001-11-13"),
    },
    {
        name: ["Hyunjin"],
        group: [16, 14],
        birthday: new Date("2000-11-15"),
    },
    {
        name: ["Gowon"],
        group: [16, 14],
        birthday: new Date("2000-11-19"),
    },
    {
        name: ["Vivi"],
        group: [16, 14],
        birthday: new Date("1996-12-09"),
    },
    {
        name: ["Isa"],
        group: [17],
        birthday: new Date("2002-01-23"),
    },
    {
        name: ["Sumin"],
        group: [17],
        birthday: new Date("2001-03-13"),
    },
    {
        name: ["Yoon"],
        group: [17],
        birthday: new Date("2004-04-14"),
    },
    {
        name: ["Seeun"],
        group: [17],
        birthday: new Date("2003-06-14"),
    },
    {
        name: ["J"],
        group: [17],
        birthday: new Date("2004-12-09"),
    },
    {
        name: ["Sieun"],
        group: [17],
        birthday: new Date("2001-08-01"),
    },
    {
        name: ["Hyebin"],
        group: [18],
        birthday: new Date("1996-01-12"),
    },
    {
        name: ["Daisy"],
        group: [-18],
        birthday: new Date("1999-01-22"),
    },
    {
        name: ["Nancy"],
        group: [18],
        birthday: new Date("2000-04-13"),
    },
    {
        name: ["Taeha"],
        group: [-18],
        birthday: new Date("1998-06-03"),
    },
    {
        name: ["Nayun"],
        group: [18],
        birthday: new Date("1998-07-31"),
    },
    {
        name: ["Yeonwoo"],
        group: [-18],
        birthday: new Date("1996-08-01"),
    },
    {
        name: ["JooE"],
        group: [18],
        birthday: new Date("1999-08-18"),
    },
    {
        name: ["Ahin"],
        group: [18],
        birthday: new Date("1999-09-27"),
    },
    {
        name: ["Jane"],
        group: [18],
        birthday: new Date("1997-12-20"),
    },
    {
        name: ["Chloe"],
        group: [19],
        birthday: new Date("2001-01-06"),
    },
    {
        name: ["Jeewon"],
        group: [19],
        birthday: new Date("1999-04-01"),
    },
    {
        name: ["Semi"],
        group: [19],
        birthday: new Date("2002-04-10"),
    },
    {
        name: ["Seline"],
        group: [19],
        birthday: new Date("2000-07-20"),
    },
    {
        name: ["Chaesol"],
        group: [19],
        birthday: new Date("1998-07-14"),
    },
    {
        name: ["Dohee"],
        group: [19],
        birthday: new Date("2002-08-01"),
    },
    {
        name: ["Haeun aka Ye Ah", "Haeun"],
        group: [19],
        birthday: new Date("1999-10-09"),
    },
    {
        name: ["Belle"],
        group: [19],
        birthday: new Date("2001-11-03"),
    },
    {
        name: ["Yoohyeon"],
        group: [20],
        birthday: new Date("1997-01-07"),
    },
    {
        name: ["Gahyeon"],
        group: [20],
        birthday: new Date("1999-02-03"),
    },
    {
        name: ["Dami"],
        group: [20],
        birthday: new Date("1997-03-07"),
    },
    {
        name: ["Handong"],
        group: [20],
        birthday: new Date("1996-03-26"),
    },
    {
        name: ["Jiu"],
        group: [20],
        birthday: new Date("1994-05-17"),
    },
    {
        name: ["Sua"],
        group: [20],
        birthday: new Date("1994-08-10"),
    },
    {
        name: ["Siyeon"],
        group: [20],
        birthday: new Date("1995-10-01"),
    },
    {
        name: ["Mia"],
        group: [21],
        birthday: new Date("2000-01-13"),
    },
    {
        name: ["Onda"],
        group: [21],
        birthday: new Date("2000-05-18"),
    },
    {
        name: ["EU"],
        group: [21],
        birthday: new Date("1998-05-19"),
    },
    {
        name: ["Aisha"],
        group: [21],
        birthday: new Date("2000-07-21"),
    },
    {
        name: ["Sihyeon"],
        group: [21],
        birthday: new Date("1999-08-05"),
    },
    {
        name: ["Yiren"],
        group: [21],
        birthday: new Date("2000-12-29"),
    },
    {
        name: ["Dosie"],
        group: [22],
        birthday: new Date("2000-02-11"),
    },
    {
        name: ["Ireh"],
        group: [22],
        birthday: new Date("2002-04-30"),
    },
    {
        name: ["Swan"],
        group: [22],
        birthday: new Date("2003-07-11"),
    },
    {
        name: ["Goeun"],
        group: [22],
        birthday: new Date("1999-09-03"),
    },
    {
        name: ["Jieun"],
        group: [-22],
        birthday: new Date("1997-09-04"),
    },
    {
        name: ["Yuki"],
        group: [22],
        birthday: new Date("2002-11-06"),
    },
    {
        name: ["Chaein"],
        group: [22],
        birthday: new Date("2002-12-05"),
    },
    {
        name: ["Jungwoo"],
        group: [23],
        birthday: new Date("1999-04-02"),
    },
    {
        name: ["Simyeong"],
        group: [23],
        birthday: new Date("1999-05-27"),
    },
    {
        name: ["Yiyeon"],
        group: [23],
        birthday: new Date("1995-05-28"),
    },
    {
        name: ["Songhee"],
        group: [23],
        birthday: new Date("1998-11-08"),
    },
    {
        name: ["Seungeun"],
        group: [23],
        birthday: new Date("2000-12-27"),
    },
    {
        name: ["I.N", "IN"],
        group: [24],
        birthday: new Date("2001-02-08"),
    },
    {
        name: ["Hyunjin"],
        group: [24],
        birthday: new Date("2000-03-20"),
    },
    {
        name: ["Changbin"],
        group: [24],
        birthday: new Date("1999-08-11"),
    },
    {
        name: ["Han"],
        group: [24],
        birthday: new Date("2000-09-14"),
    },
    {
        name: ["Felix"],
        group: [24],
        birthday: new Date("2000-09-15"),
    },
    {
        name: ["Seungmin"],
        group: [24],
        birthday: new Date("2000-09-22"),
    },
    {
        name: ["Bang Chan", "BangChan"],
        group: [24],
        birthday: new Date("1997-10-03"),
    },
    {
        name: ["Lee Know", "LeeKnow"],
        group: [24],
        birthday: new Date("1998-10-25"),
    },
    {
        name: ["D.O.", "DO"],
        group: [25],
        birthday: new Date("1993-01-12"),
    },
    {
        name: ["Kai"],
        group: [25],
        birthday: new Date("1994-01-14"),
    },
    {
        name: ["Tao"],
        group: [-25],
        birthday: new Date("1993-03-02"),
    },
    {
        name: ["Baekhyun"],
        group: [25],
        birthday: new Date("1992-03-06"),
    },
    {
        name: ["Xiumin"],
        group: [25],
        birthday: new Date("1990-03-26"),
    },
    {
        name: ["Sehun"],
        group: [25],
        birthday: new Date("1994-04-12"),
    },
    {
        name: ["Luhan"],
        group: [-25],
        birthday: new Date("1990-04-20"),
    },
    {
        name: ["Suho"],
        group: [25],
        birthday: new Date("1991-05-22"),
    },
    {
        name: ["Chen"],
        group: [25],
        birthday: new Date("1992-09-21"),
    },
    {
        name: ["Lay"],
        group: [-25],
        birthday: new Date("1991-10-07"),
    },
    {
        name: ["Kris Wu", "Kris", "KrisWu"],
        group: [-25],
        birthday: new Date("1990-11-06"),
    },
    {
        name: ["Chanyeol"],
        group: [25],
        birthday: new Date("1992-11-27"),
    },
    {
        name: ["Yeongeun"],
        group: [26],
        birthday: new Date("1996-07-08"),
    },
    {
        name: ["Arem"],
        group: [26],
        birthday: new Date("1995-09-27"),
    },
    {
        name: ["Iree"],
        group: [26],
        birthday: new Date("1995-10-17"),
    },
    {
        name: ["Jayoung"],
        group: [26],
        birthday: new Date("1996-10-27"),
    },
    {
        name: ["Hyunjung"],
        group: [26],
        birthday: new Date("1996-10-31"),
    },
    {
        name: ["Haeyoon"],
        group: [27],
        birthday: new Date("1996-01-10"),
    },
    {
        name: ["Bora"],
        group: [27],
        birthday: new Date("1999-03-03"),
    },
    {
        name: ["Yuju"],
        group: [27],
        birthday: new Date("1997-03-05"),
    },
    {
        name: ["Chaerin"],
        group: [27],
        birthday: new Date("2002-03-13"),
    },
    {
        name: ["Remi"],
        group: [27],
        birthday: new Date("2001-04-26"),
    },
    {
        name: ["Jiwon"],
        group: [27],
        birthday: new Date("2000-09-04"),
    },
    {
        name: ["May"],
        group: [27],
        birthday: new Date("2004-11-16"),
    },
    {
        name: ["Hina"],
        group: [28],
        birthday: new Date("2003-04-07"),
    },
    {
        name: ["Juhyeon"],
        group: [28],
        birthday: new Date("2004-04-08"),
    },
    {
        name: ["Yujeong"],
        group: [28],
        birthday: new Date("2004-06-14"),
    },
    {
        name: ["Huiyeon"],
        group: [-28],
        birthday: new Date("2005-08-01"),
    },
    {
        name: ["Sangah"],
        group: [28],
        birthday: new Date("2002-09-04"),
    },
    {
        name: ["Chowon"],
        group: [28],
        birthday: new Date("2002-09-16"),
    },
    {
        name: ["Jian"],
        group: [-28],
        birthday: new Date("2006-11-04"),
    },
    {
        name: ["Nayoung"],
        group: [28],
        birthday: new Date("2002-11-30"),
    },
    {
        name: ["Hyungwon"],
        group: [29],
        birthday: new Date("1994-01-15"),
    },
    {
        name: ["I.M", "IM"],
        group: [29],
        birthday: new Date("1996-01-26"),
    },
    {
        name: ["Wonho"],
        group: [-29],
        birthday: new Date("1993-03-01"),
    },
    {
        name: ["Shownu"],
        group: [29],
        birthday: new Date("1992-06-18"),
    },
    {
        name: ["Joohoney"],
        group: [29],
        birthday: new Date("1994-10-06"),
    },
    {
        name: ["Minhyuk"],
        group: [29],
        birthday: new Date("1993-11-03"),
    },
    {
        name: ["Kihyun"],
        group: [29],
        birthday: new Date("1993-11-22"),
    },
    {
        name: ["Daehwi"],
        group: [30],
        birthday: new Date("2001-01-29"),
    },
    {
        name: ["Donghyun"],
        group: [30],
        birthday: new Date("1998-09-17"),
    },
    {
        name: ["Woong"],
        group: [30],
        birthday: new Date("1997-10-15"),
    },
    {
        name: ["Woojin"],
        group: [30],
        birthday: new Date("1999-11-02"),
    },
    {
        name: ["Youngmin"],
        group: [-30],
        birthday: new Date("1995-12-25"),
    },
    {
        name: ["Jungwon"],
        group: [31],
        birthday: new Date("2004-02-09"),
    },
    {
        name: ["Jay"],
        group: [31],
        birthday: new Date("2002-04-20"),
    },
    {
        name: ["Sunoo"],
        group: [31],
        birthday: new Date("2003-06-24"),
    },
    {
        name: ["Heeseung"],
        group: [31],
        birthday: new Date("2001-10-15"),
    },
    {
        name: ["Sunghoon"],
        group: [31],
        birthday: new Date("2002-12-08"),
    },
    {
        name: ["Ni-Ki", "Niki"],
        group: [31],
        birthday: new Date("2005-12-09"),
    },
    {
        name: ["Xion"],
        group: [32],
        birthday: new Date("2000-01-10"),
    },
    {
        name: ["Seoho"],
        group: [32],
        birthday: new Date("1996-06-07"),
    },
    {
        name: ["Keonhee"],
        group: [32],
        birthday: new Date("1998-06-27"),
    },
    {
        name: ["Leedo"],
        group: [32],
        birthday: new Date("1997-07-26"),
    },
    {
        name: ["Hwanwoong"],
        group: [32],
        birthday: new Date("1998-08-26"),
    },
    {
        name: ["Ravn"],
        group: [-32],
        birthday: new Date("1995-09-02"),
    },
    {
        name: ["Kun"],
        group: [33],
        birthday: new Date("1996-01-01"),
    },
    {
        name: ["Lucas"],
        group: [-33],
        birthday: new Date("1999-01-25"),
    },
    {
        name: ["Doyoung"],
        group: [33],
        birthday: new Date("1996-02-01"),
    },
    {
        name: ["Jisung"],
        group: [33],
        birthday: new Date("2002-02-05"),
    },
    {
        name: ["Johnny"],
        group: [33],
        birthday: new Date("1995-02-09"),
    },
    {
        name: ["Jaehyun"],
        group: [33],
        birthday: new Date("1997-02-14"),
    },
    {
        name: ["Jungwoo"],
        group: [33],
        birthday: new Date("1998-02-19"),
    },
    {
        name: ["Ten"],
        group: [33],
        birthday: new Date("1996-02-27"),
    },
    {
        name: ["Renjun"],
        group: [33],
        birthday: new Date("2000-03-23"),
    },
    {
        name: ["Jeno"],
        group: [33],
        birthday: new Date("2000-04-23"),
    },
    {
        name: ["Haechan"],
        group: [33],
        birthday: new Date("2000-06-06"),
    },
    {
        name: ["Taeil"],
        group: [33],
        birthday: new Date("1994-06-14"),
    },
    {
        name: ["Taeyong"],
        group: [33],
        birthday: new Date("1995-07-01"),
    },
    {
        name: ["Mark"],
        group: [33],
        birthday: new Date("1999-08-02"),
    },
    {
        name: ["Xiaojun"],
        group: [33],
        birthday: new Date("1999-08-08"),
    },
    {
        name: ["Jaemin"],
        group: [33],
        birthday: new Date("2000-08-13"),
    },
    {
        name: ["Sungchan"],
        group: [-33],
        birthday: new Date("2001-09-13"),
    },
    {
        name: ["Hendery"],
        group: [33],
        birthday: new Date("1999-09-28"),
    },
    {
        name: ["Yangyang"],
        group: [33],
        birthday: new Date("2000-10-10"),
    },
    {
        name: ["Yuta"],
        group: [33],
        birthday: new Date("1995-10-26"),
    },
    {
        name: ["Winwin"],
        group: [33],
        birthday: new Date("1997-10-28"),
    },
    {
        name: ["Chenle"],
        group: [33],
        birthday: new Date("2001-11-22"),
    },
    {
        name: ["Shotaro"],
        group: [-33],
        birthday: new Date("2000-11-25"),
    },
    {
        name: ["J-Hope", "JHope"],
        group: [34],
        birthday: new Date("1994-02-18"),
    },
    {
        name: ["Suga"],
        group: [34],
        birthday: new Date("1993-03-09"),
    },
    {
        name: ["Jungkook"],
        group: [34],
        birthday: new Date("1997-09-01"),
    },
    {
        name: ["RM"],
        group: [34],
        birthday: new Date("1994-09-12"),
    },
    {
        name: ["Jimin"],
        group: [34],
        birthday: new Date("1995-10-13"),
    },
    {
        name: ["Jin"],
        group: [34],
        birthday: new Date("1992-12-04"),
    },
    {
        name: ["V"],
        group: [34],
        birthday: new Date("1995-12-30"),
    },
    {
        name: ["Sungmin"],
        group: [35],
        birthday: new Date("1986-01-01"),
    },
    {
        name: ["Kyuhyun"],
        group: [35],
        birthday: new Date("1988-02-03"),
    },
    {
        name: ["Eunhyuk"],
        group: [35],
        birthday: new Date("1986-04-04"),
    },
    {
        name: ["Siwon"],
        group: [35],
        birthday: new Date("1986-04-07"),
    },
    {
        name: ["Ryeowook"],
        group: [35],
        birthday: new Date("1987-06-21"),
    },
    {
        name: ["Leeteuk"],
        group: [35],
        birthday: new Date("1983-07-01"),
    },
    {
        name: ["Heechul"],
        group: [35],
        birthday: new Date("1983-07-10"),
    },
    {
        name: ["Yesung"],
        group: [35],
        birthday: new Date("1984-08-24"),
    },
    {
        name: ["Shindong"],
        group: [35],
        birthday: new Date("1985-09-28"),
    },
    {
        name: ["Donghae"],
        group: [35],
        birthday: new Date("1986-10-15"),
    },
    {
        name: ["Haram"],
        group: [36],
        birthday: new Date("2001-01-13"),
    },
    {
        name: ["Suhyeon"],
        group: [36],
        birthday: new Date("2000-01-15"),
    },
    {
        name: ["Sheon"],
        group: [36],
        birthday: new Date("2003-01-28"),
    },
    {
        name: ["Haruna"],
        group: [36],
        birthday: new Date("2006-01-30"),
    },
    {
        name: ["Siyoon"],
        group: [36],
        birthday: new Date("2005-02-16"),
    },
    {
        name: ["Moon Sua", "MoonSua"],
        group: [36],
        birthday: new Date("1999-09-09"),
    },
    {
        name: ["Tsuki"],
        group: [36],
        birthday: new Date("2002-09-21"),
    },
    {
        name: ["Donghun"],
        group: [37],
        birthday: new Date("1993-02-28"),
    },
    {
        name: ["Wow"],
        group: [37],
        birthday: new Date("1993-03-15"),
    },
    {
        name: ["Jun"],
        group: [37],
        birthday: new Date("1994-06-02"),
    },
    {
        name: ["Kim Byeongkwan", "KimByeongkwan"],
        group: [37],
        birthday: new Date("1996-08-13"),
    },
    {
        name: ["Chan"],
        group: [37],
        birthday: new Date("1997-12-31"),
    },
    {
        name: ["Yunho"],
        group: [38],
        birthday: new Date("1999-03-23"),
    },
    {
        name: ["Seonghwa"],
        group: [38],
        birthday: new Date("1998-04-03"),
    },
    {
        name: ["Yeosang"],
        group: [38],
        birthday: new Date("1999-06-15"),
    },
    {
        name: ["San"],
        group: [38],
        birthday: new Date("1999-07-10"),
    },
    {
        name: ["Mingi"],
        group: [38],
        birthday: new Date("1999-08-09"),
    },
    {
        name: ["Jongho"],
        group: [38],
        birthday: new Date("2000-10-12"),
    },
    {
        name: ["Hongjoong"],
        group: [38],
        birthday: new Date("1998-11-07"),
    },
    {
        name: ["Wooyoung"],
        group: [38],
        birthday: new Date("1999-11-26"),
    },
    {
        name: ["Moonbin"],
        group: [39],
        birthday: new Date("1998-01-26"),
    },
    {
        name: ["Rocky"],
        group: [-39],
        birthday: new Date("1999-02-25"),
    },
    {
        name: ["MJ"],
        group: [39],
        birthday: new Date("1994-03-05"),
    },
    {
        name: ["JinJin"],
        group: [39],
        birthday: new Date("1996-03-15"),
    },
    {
        name: ["Sanha"],
        group: [39],
        birthday: new Date("2000-03-21"),
    },
    {
        name: ["Eunwoo"],
        group: [39],
        birthday: new Date("1997-03-30"),
    },
    {
        name: ["So Junghwan", "SoJunghwan", "Junghwan"],
        group: [40],
        birthday: new Date("2005-02-18"),
    },
    {
        name: ["Jihoon"],
        group: [40],
        birthday: new Date("2000-03-14"),
    },
    {
        name: ["Yoshi"],
        group: [40],
        birthday: new Date("2000-03-15"),
    },
    {
        name: ["Mashiho"],
        group: [-40],
        birthday: new Date("2001-03-25"),
    },
    {
        name: ["Haruto"],
        group: [40],
        birthday: new Date("2004-04-05"),
    },
    {
        name: ["Hyunsuk"],
        group: [40],
        birthday: new Date("1999-04-21"),
    },
    {
        name: ["Bang Yedam", "BangYedam"],
        group: [-40],
        birthday: new Date("2002-05-07"),
    },
    {
        name: ["Jaehyuk"],
        group: [40],
        birthday: new Date("2001-07-23"),
    },
    {
        name: ["Asahi"],
        group: [40],
        birthday: new Date("2001-08-20"),
    },
    {
        name: ["Junkyu"],
        group: [40],
        birthday: new Date("2000-09-09"),
    },
    {
        name: ["Jeongwoo"],
        group: [40],
        birthday: new Date("2004-09-28"),
    },
    {
        name: ["Doyoung"],
        group: [40],
        birthday: new Date("2003-12-04"),
    },
    {
        name: ["Riwon"],
        group: [41],
        birthday: new Date("2007-01-11"),
    },
    {
        name: ["Boeun"],
        group: [41],
        birthday: new Date("2008-02-11"),
    },
    {
        name: ["Seonyou"],
        group: [41],
        birthday: new Date("2008-03-20"),
    },
    {
        name: ["Chaewon"],
        group: [41],
        birthday: new Date("2003-06-04"),
    },
    {
        name: ["Hyungseo"],
        group: [41],
        birthday: new Date("2001-06-25"),
    },
    {
        name: ["Jimin"],
        group: [41],
        birthday: new Date("2007-11-25"),
    },
    {
        name: ["Hyeju"],
        group: [41],
        birthday: new Date("2003-12-09"),
    },
    {
        name: ["Sion"],
        group: [42],
        birthday: new Date("2001-03-07"),
    },
    {
        name: ["YeYoung"],
        group: [42],
        birthday: new Date("2000-05-31"),
    },
    {
        name: ["Andamiro"],
        group: [42],
        birthday: new Date("2003-05-06"),
    },
    {
        name: ["Mika"],
        group: [42],
        birthday: new Date("2002-01-08"),
    },
    {
        name: ["Zoe"],
        group: [42],
        birthday: new Date("2002-04-12"),
    },
    {
        name: ["Evie"],
        group: [43],
        birthday: new Date("2002-05-22"),
    },
    {
        name: ["Ahra"],
        group: [43],
        birthday: new Date("2004-02-20"),
    },
    {
        name: ["Nicole"],
        group: [43],
        birthday: new Date("2005-07-09"),
    },
    {
        name: ["Yan"],
        group: [43],
        birthday: new Date("2005-07-11"),
    },
    {
        name: ["Vivi"],
        group: [43],
        birthday: new Date("2005-09-01"),
    },
    {
        name: ["E.Ji", "EJi"],
        group: [44],
        birthday: new Date("2000-11-08"),
    },
    {
        name: ["Jiyoon"],
        group: [44],
        birthday: new Date("2000-09-12"),
    },
    {
        name: ["Jackie"],
        group: [44],
        birthday: new Date("2001-11-17"),
    },
    {
        name: ["Joonie"],
        group: [44],
        birthday: new Date("2002-05-24"),
    },
    {
        name: ["Chaerin"],
        group: [44],
        birthday: new Date("2003-03-31"),
    },
    {
        name: ["Yeju"],
        group: [44],
        birthday: new Date("2004-09-01"),
    },
    {
        name: ["Chowon"],
        group: [44],
        birthday: new Date("2005-08-18"),
    },
    {
        name: ["JinE"],
        group: [-45],
        birthday: new Date("1995-01-22"),
    },
    {
        name: ["Seunghee"],
        group: [45],
        birthday: new Date("1996-01-25"),
    },
    {
        name: ["Jiho"],
        group: [-45],
        birthday: new Date("1997-04-04"),
    },
    {
        name: ["Mimi"],
        group: [45],
        birthday: new Date("1995-05-01"),
    },
    {
        name: ["Arin"],
        group: [45],
        birthday: new Date("1999-06-18"),
    },
    {
        name: ["Hyojung"],
        group: [45],
        birthday: new Date("1994-07-28"),
    },
    {
        name: ["Yubin"],
        group: [45],
        birthday: new Date("1997-09-09"),
    },
    {
        name: ["YooA"],
        group: [45],
        birthday: new Date("1995-09-17"),
    },
    {
        name: ["J.Seph", "JSeph"],
        group: [46],
        birthday: new Date("1992-06-21"),
    },
    {
        name: ["Somin"],
        group: [46],
        birthday: new Date("1996-08-22"),
    },
    {
        name: ["Jiwoo"],
        group: [46],
        birthday: new Date("1996-10-04"),
    },
    {
        name: ["BM"],
        group: [46],
        birthday: new Date("1992-10-20"),
    },
    {
        name: ["Yuna"],
        group: [47],
        birthday: new Date("1993-04-06"),
    },
    {
        name: ["Yujeong"],
        group: [47],
        birthday: new Date("1991-05-02"),
    },
    {
        name: ["Eunji"],
        group: [47],
        birthday: new Date("1992-07-19"),
    },
    {
        name: ["Minyoung"],
        group: [47],
        birthday: new Date("1990-09-12"),
    },
    {
        name: ["Eunbin"],
        group: [78],
        birthday: new Date("2000-01-06"),
    },
    {
        name: ["Yeeun"],
        group: [78],
        birthday: new Date("1998-08-10"),
    },
    {
        name: ["Seunghee"],
        group: [78],
        birthday: new Date("1995-10-10"),
    },
    {
        name: ["Elkie"],
        group: [78],
        birthday: new Date("1998-11-02"),
    },
    {
        name: ["Seungyeon"],
        group: [78],
        birthday: new Date("1996-11-06"),
    },
    {
        name: ["Sorn"],
        group: [-78],
        birthday: new Date("1996-11-18"),
    },
    {
        name: ["Wooyeon"],
        group: [48],
        birthday: new Date("2003-02-11"),
    },
    {
        name: ["Nana"],
        group: [48],
        birthday: new Date("2001-03-09"),
    },
    {
        name: ["Lucy"],
        group: [48],
        birthday: new Date("2004-04-09"),
    },
    {
        name: ["Minseo"],
        group: [48],
        birthday: new Date("2004-08-12"),
    },
    {
        name: ["Sora"],
        group: [48],
        birthday: new Date("2003-08-30"),
    },
    {
        name: ["Songyee"],
        group: [-48],
        birthday: new Date("2004-09-25"),
    },
    {
        name: ["ChaeY"],
        group: [-49],
        birthday: new Date("2003-01-06"),
    },
    {
        name: ["Karin"],
        group: [49],
        birthday: new Date("2000-04-23"),
    },
    {
        name: ["Wooah"],
        group: [49],
        birthday: new Date("1997-06-20"),
    },
    {
        name: ["Hyejin"],
        group: [49],
        birthday: new Date("2000-07-13"),
    },
    {
        name: ["Swan"],
        group: [49],
        birthday: new Date("2000-12-28"),
    },
    {
        name: ["Lola"],
        group: [50],
        birthday: new Date("2001-02-22"),
    },
    {
        name: ["Satbyeol"],
        group: [-50],
        birthday: new Date("2001-02-27"),
    },
    {
        name: ["Sua"],
        group: [50],
        birthday: new Date("2003-02-24"),
    },
    {
        name: ["Ella"],
        group: [-50],
        birthday: new Date("1998-03-26"),
    },
    {
        name: ["Rinji"],
        group: [50],
        birthday: new Date("2006-05-05"),
    },
    {
        name: ["Dia"],
        group: [50],
        birthday: new Date("2001-07-16"),
    },
    {
        name: ["Dajeong"],
        group: [50],
        birthday: new Date("2003-07-31"),
    },
    {
        name: ["Yunji"],
        group: [-51],
        birthday: new Date("2007-01-09"),
    },
    {
        name: ["Takara"],
        group: [51],
        birthday: new Date("2005-01-19"),
    },
    {
        name: ["Seira"],
        group: [51],
        birthday: new Date("2004-01-27"),
    },
    {
        name: ["Jieun"],
        group: [51],
        birthday: new Date("2005-03-05"),
    },
    {
        name: ["Nami"],
        group: [51],
        birthday: new Date("2004-06-08"),
    },
    {
        name: ["MinMin"],
        group: [-51],
        birthday: new Date("2006-07-02"),
    },
    {
        name: ["Minji"],
        group: [51],
        birthday: new Date("2006-09-26"),
    },
    {
        name: ["Yeoreum"],
        group: [52],
        birthday: new Date("1999-01-10"),
    },
    {
        name: ["Xuan Yi", "XuanYi"],
        group: [52],
        birthday: new Date("1995-01-26"),
    },
    {
        name: ["Luda"],
        group: [52],
        birthday: new Date("1997-03-06"),
    },
    {
        name: ["Dawon"],
        group: [52],
        birthday: new Date("1997-04-16"),
    },
    {
        name: ["Dayoung"],
        group: [52],
        birthday: new Date("1999-05-14"),
    },
    {
        name: ["Eunseo"],
        group: [52],
        birthday: new Date("1998-05-27"),
    },
    {
        name: ["Cheng Xiao", "ChengXiao"],
        group: [52],
        birthday: new Date("1998-07-15"),
    },
    {
        name: ["Yeonjung"],
        group: [52],
        birthday: new Date("1999-08-03"),
    },
    {
        name: ["Bona"],
        group: [52],
        birthday: new Date("1995-08-19"),
    },
    {
        name: ["Soobin"],
        group: [52],
        birthday: new Date("1996-09-14"),
    },
    {
        name: ["Mei Qi", "MeiQi"],
        group: [52],
        birthday: new Date("1998-10-15"),
    },
    {
        name: ["Exy"],
        group: [52],
        birthday: new Date("1995-11-06"),
    },
    {
        name: ["Seola"],
        group: [52],
        birthday: new Date("1994-12-24"),
    },
    {
        name: ["Danielle"],
        group: [53],
        birthday: new Date("2005-04-11"),
    },
    {
        name: ["Hyein"],
        group: [53],
        birthday: new Date("2008-04-21"),
    },
    {
        name: ["Minji"],
        group: [53],
        birthday: new Date("2004-05-07"),
    },
    {
        name: ["Haerin"],
        group: [53],
        birthday: new Date("2006-05-15"),
    },
    {
        name: ["Hanni"],
        group: [53],
        birthday: new Date("2004-10-06"),
    },
    {
        name: ["Mimi"],
        group: [54],
        birthday: new Date("1993-01-01"),
    },
    {
        name: ["Hana"],
        group: [54],
        birthday: new Date("1993-04-30"),
    },
    {
        name: ["Haebin"],
        group: [54],
        birthday: new Date("1995-08-16"),
    },
    {
        name: ["Sejeong"],
        group: [54],
        birthday: new Date("1996-08-28"),
    },
    {
        name: ["Sally"],
        group: [54],
        birthday: new Date("1996-10-23"),
    },
    {
        name: ["Soyee"],
        group: [54],
        birthday: new Date("1996-11-21"),
    },
    {
        name: ["Nayoung"],
        group: [54],
        birthday: new Date("1995-11-23"),
    },
    {
        name: ["Kang Mina", "KangMina", "Mina"],
        group: [54],
        birthday: new Date("1999-12-04"),
    },
    {
        name: ["Dahyun"],
        group: [55],
        birthday: new Date("2003-01-08"),
    },
    {
        name: ["Yeonji"],
        group: [55],
        birthday: new Date("2008-01-08"),
    },
    {
        name: ["Yubin"],
        group: [55],
        birthday: new Date("2005-02-03"),
    },
    {
        name: ["Yooyeon"],
        group: [55],
        birthday: new Date("2001-02-09"),
    },
    {
        name: ["Kotone"],
        group: [55],
        birthday: new Date("2004-03-10"),
    },
    {
        name: ["Hyerin"],
        group: [55],
        birthday: new Date("2007-04-12"),
    },
    {
        name: ["Lynn"],
        group: [55],
        birthday: new Date("2007-04-12"),
    },
    {
        name: ["Xinyu"],
        group: [55],
        birthday: new Date("2002-05-25"),
    },
    {
        name: ["Nien"],
        group: [55],
        birthday: new Date("2003-06-02"),
    },
    {
        name: ["Seoyeon"],
        group: [55],
        birthday: new Date("2003-08-06"),
    },
    {
        name: ["Soomin"],
        group: [55],
        birthday: new Date("2007-10-03"),
    },
    {
        name: ["Nakyoung"],
        group: [55],
        birthday: new Date("2002-10-13"),
    },
    {
        name: ["Sohyun"],
        group: [55],
        birthday: new Date("2002-10-13"),
    },
    {
        name: ["Jiwoo"],
        group: [55],
        birthday: new Date("2005-10-24"),
    },
    {
        name: ["Chaeyeon"],
        group: [55],
        birthday: new Date("2004-12-04"),
    },
    {
        name: ["Kaede"],
        group: [55],
        birthday: new Date("2005-12-20"),
    },
    {
        name: ["Mayu"],
        group: [55],
        birthday: new Date("2002-05-12"),
    },
    {
        name: ["Shion"],
        group: [55],
        birthday: new Date("2006-04-03"),
    },
    {
        name: ["Hayeon"],
        group: [55],
        birthday: new Date("2007-08-01"),
    },
    {
        name: ["Joobin"],
        group: [55],
        birthday: new Date("2009-01-16"),
    },
    {
        name: ["Yuto"],
        group: [56],
        birthday: new Date("1998-01-23"),
    },
    {
        name: ["Kino"],
        group: [56],
        birthday: new Date("1998-01-27"),
    },
    {
        name: ["Wooseok"],
        group: [56],
        birthday: new Date("1998-01-31"),
    },
    {
        name: ["Yeo One", "YeoOne"],
        group: [56],
        birthday: new Date("1996-03-27"),
    },
    {
        name: ["Jinho"],
        group: [56],
        birthday: new Date("1992-04-17"),
    },
    {
        name: ["Hongseok"],
        group: [56],
        birthday: new Date("1994-04-17"),
    },
    {
        name: ["Hui"],
        group: [56],
        birthday: new Date("1993-08-28"),
    },
    {
        name: ["Yanan"],
        group: [56],
        birthday: new Date("1996-10-25"),
    },
    {
        name: ["Shinwon"],
        group: [56],
        birthday: new Date("1995-12-11"),
    },
    {
        name: ["Minhee"],
        group: [57],
        birthday: new Date("2002-09-17"),
    },
    {
        name: ["Serim"],
        group: [57],
        birthday: new Date("1999-03-03"),
    },
    {
        name: ["Allen"],
        group: [57],
        birthday: new Date("1999-04-26"),
    },
    {
        name: ["Jungmo"],
        group: [57],
        birthday: new Date("2000-02-05"),
    },
    {
        name: ["Woobin"],
        group: [57],
        birthday: new Date("2000-10-16"),
    },
    {
        name: ["Wonjin"],
        group: [57],
        birthday: new Date("2001-03-22"),
    },
    {
        name: ["Hyeongjun"],
        group: [57],
        birthday: new Date("2002-11-30"),
    },
    {
        name: ["Taeyoung"],
        group: [57],
        birthday: new Date("2003-01-27"),
    },
    {
        name: ["Seongmin"],
        group: [57],
        birthday: new Date("2003-08-01"),
    },
    {
        name: ["Yeonsu"],
        group: [58],
        birthday: new Date("2003-02-19"),
    },
    {
        name: ["Seowon"],
        group: [58],
        birthday: new Date("2004-04-26"),
    },
    {
        name: ["Sena"],
        group: [58],
        birthday: new Date("2005-10-12"),
    },
    {
        name: ["Seungchae"],
        group: [58],
        birthday: new Date("2006-10-26"),
    },
    {
        name: ["Chaeeun"],
        group: [58],
        birthday: new Date("2005-12-10"),
    },
    {
        name: ["Chiquita"],
        group: [59],
        birthday: new Date("2009-02-17"),
    },
    {
        name: ["Ahyeon"],
        group: [59],
        birthday: new Date("2007-04-11"),
    },
    {
        name: ["Asa"],
        group: [59],
        birthday: new Date("2006-04-17"),
    },
    {
        name: ["Pharita"],
        group: [59],
        birthday: new Date("2005-08-26"),
    },
    {
        name: ["Rora"],
        group: [59],
        birthday: new Date("2008-10-14"),
    },
    {
        name: ["Rami"],
        group: [59],
        birthday: new Date("2007-10-17"),
    },
    {
        name: ["Ruka"],
        group: [59],
        birthday: new Date("2002-3-20"),
    },
    {
        name: ["Chisa"],
        group: [60],
        birthday: new Date("2002-01-17"),
    },
    {
        name: ["Hinata"],
        group: [60],
        birthday: new Date("2002-06-11"),
    },
    {
        name: ["Jurin"],
        group: [60],
        birthday: new Date("2002-06-19"),
    },
    {
        name: ["Maya"],
        group: [60],
        birthday: new Date("2005-08-10"),
    },
    {
        name: ["Juria"],
        group: [60],
        birthday: new Date("2004-11-28"),
    },
    {
        name: ["Cocona"],
        group: [60],
        birthday: new Date("2005-12-06"),
    },
    {
        name: ["Harvey"],
        group: [60],
        birthday: new Date("2002-12-18"),
    },
    {
        name: ["Shana"],
        group: [61],
        birthday: new Date("2003-03-13"),
    },
    {
        name: ["Yue"],
        group: [61],
        birthday: new Date("2004-06-03"),
    },
    {
        name: ["Bessie"],
        group: [61],
        birthday: new Date("2004-07-15"),
    },
    {
        name: ["Haeun"],
        group: [61],
        birthday: new Date("2008-11-02"),
    },
    {
        name: ["Seowon"],
        group: [61],
        birthday: new Date("2006-12-05"),
    },
    {
        name: ["Chanty"],
        group: [61],
        birthday: new Date("2002-12-15"),
    },
    {
        name: ["Seungkwan"],
        group: [62],
        birthday: new Date("1998-01-16"),
    },
    {
        name: ["Dino"],
        group: [62],
        birthday: new Date("1999-02-11"),
    },
    {
        name: ["DK"],
        group: [62],
        birthday: new Date("1997-02-18"),
    },
    {
        name: ["Vernon"],
        group: [62],
        birthday: new Date("1998-02-18"),
    },
    {
        name: ["Mingyu"],
        group: [62],
        birthday: new Date("1997-04-06"),
    },
    {
        name: ["Jun"],
        group: [62],
        birthday: new Date("1996-06-10"),
    },
    {
        name: ["Hoshi"],
        group: [62],
        birthday: new Date("1996-06-15"),
    },
    {
        name: ["Wonwoo"],
        group: [62],
        birthday: new Date("1996-07-17"),
    },
    {
        name: ["S.Coups", "SCoups"],
        group: [62],
        birthday: new Date("1995-08-08"),
    },
    {
        name: ["Jeonghan"],
        group: [62],
        birthday: new Date("1995-10-04"),
    },
    {
        name: ["The8"],
        group: [62],
        birthday: new Date("1997-11-07"),
    },
    {
        name: ["Woozi"],
        group: [62],
        birthday: new Date("1996-11-22"),
    },
    {
        name: ["Joshua"],
        group: [62],
        birthday: new Date("1995-12-30"),
    },
    {
        name: ["Suyun"],
        group: [63],
        birthday: new Date("2001-03-17"),
    },
    {
        name: ["Dahyun"],
        group: [63],
        birthday: new Date("2005-04-29"),
    },
    {
        name: ["Sohee"],
        group: [63],
        birthday: new Date("2003-08-14"),
    },
    {
        name: ["Juri"],
        group: [63],
        birthday: new Date("1997-10-03"),
    },
    {
        name: ["Yunkyoung"],
        group: [63],
        birthday: new Date("2001-11-01"),
    },
    {
        name: ["Yeonhee"],
        group: [63],
        birthday: new Date("2000-12-06"),
    },
    {
        name: ["Sei"],
        group: [64],
        birthday: new Date("2000-01-07"),
    },
    {
        name: ["Suyeon"],
        group: [64],
        birthday: new Date("1997-04-20"),
    },
    {
        name: ["Elly"],
        group: [64],
        birthday: new Date("1998-07-20"),
    },
    {
        name: ["Lucy"],
        group: [64],
        birthday: new Date("2002-08-31"),
    },
    {
        name: ["Rina"],
        group: [64],
        birthday: new Date("2001-09-27"),
    },
    {
        name: ["Lua"],
        group: [64],
        birthday: new Date("2000-10-06"),
    },
    {
        name: ["Yoojung"],
        group: [64],
        birthday: new Date("1999-11-12"),
    },
    {
        name: ["Doyeon"],
        group: [64],
        birthday: new Date("1999-12-04"),
    },
    {
        name: ["Seolhyun"],
        group: [65],
        birthday: new Date("1995-01-03"),
    },
    {
        name: ["Jimin"],
        group: [-65],
        birthday: new Date("1991-01-08"),
    },
    {
        name: ["Choa"],
        group: [-65],
        birthday: new Date("1990-03-06"),
    },
    {
        name: ["Youkyung"],
        group: [-65],
        birthday: new Date("1993-03-15"),
    },
    {
        name: ["Chanmi", "Dohwa"],
        group: [65],
        birthday: new Date("1996-06-19"),
    },
    {
        name: ["Hyejeong"],
        group: [65],
        birthday: new Date("1993-08-10"),
    },
    {
        name: ["Mina"],
        group: [-65],
        birthday: new Date("1993-09-21"),
    },
    {
        name: ["Yuna"],
        group: [-65],
        birthday: new Date("1992-12-30"),
    },
    {
        name: ["Kelly"],
        group: [66],
        birthday: new Date("2002-01-16"),
    },
    {
        name: ["Songsun"],
        group: [66],
        birthday: new Date("1997-03-22"),
    },
    {
        name: ["Hyunbin"],
        group: [66],
        birthday: new Date("2004-03-26"),
    },
    {
        name: ["Mire"],
        group: [66],
        birthday: new Date("2006-03-26"),
    },
    {
        name: ["Jia"],
        group: [66],
        birthday: new Date("2005-06-30"),
    },
    {
        name: ["Jinha"],
        group: [-66],
        birthday: new Date("2003-11-21"),
    },
    {
        name: ["Soeun"],
        group: [66],
        birthday: new Date("2005-12-10"),
    },
    {
        name: ["Saerom"],
        group: [67],
        birthday: new Date("1997-01-07"),
    },
    {
        name: ["Seoyeon"],
        group: [67],
        birthday: new Date("2000-01-22"),
    },
    {
        name: ["Jiwon"],
        group: [67],
        birthday: new Date("1998-03-20"),
    },
    {
        name: ["Jiheon"],
        group: [67],
        birthday: new Date("2003-04-17"),
    },
    {
        name: ["Chaeyoung"],
        group: [67],
        birthday: new Date("2000-05-14"),
    },
    {
        name: ["Nagyung"],
        group: [67],
        birthday: new Date("2000-06-01"),
    },
    {
        name: ["Hayoung"],
        group: [67],
        birthday: new Date("1997-09-29"),
    },
    {
        name: ["Jisun"],
        group: [67],
        birthday: new Date("1998-11-23"),
    },
    {
        name: ["Gyuri"],
        group: [-67],
        birthday: new Date("1997-12-27"),
    },
    {
        name: ["Sooyoung"],
        group: [68],
        birthday: new Date("1990-02-10"),
    },
    {
        name: ["Taeyeon"],
        group: [68],
        birthday: new Date("1989-03-09"),
    },
    {
        name: ["Jessica"],
        group: [-68],
        birthday: new Date("1989-04-18"),
    },
    {
        name: ["Sunny"],
        group: [68],
        birthday: new Date("1989-05-15"),
    },
    {
        name: ["Yoona"],
        group: [68],
        birthday: new Date("1990-05-30"),
    },
    {
        name: ["Seohyun"],
        group: [68],
        birthday: new Date("1991-06-28"),
    },
    {
        name: ["Tiffany"],
        group: [68],
        birthday: new Date("1989-08-01"),
    },
    {
        name: ["Hyoyeon"],
        group: [68],
        birthday: new Date("1989-09-22"),
    },
    {
        name: ["Yuri"],
        group: [68],
        birthday: new Date("1989-12-05"),
    },
    {
        name: ["Chorong"],
        group: [69],
        birthday: new Date("1991-03-03"),
    },
    {
        name: ["Namjoo"],
        group: [69],
        birthday: new Date("1995-04-15"),
    },
    {
        name: ["Hayoung"],
        group: [69],
        birthday: new Date("1996-07-19"),
    },
    {
        name: ["Bomi"],
        group: [69],
        birthday: new Date("1993-08-13"),
    },
    {
        name: ["Eunji"],
        group: [69],
        birthday: new Date("1993-08-18"),
    },
    {
        name: ["Belle"],
        group: [70],
        birthday: new Date("2004-03-20"),
    },
    {
        name: ["Julie"],
        group: [70],
        birthday: new Date("2000-03-29"),
    },
    {
        name: ["Haneul"],
        group: [70],
        birthday: new Date("2005-05-25"),
    },
    {
        name: ["Natty"],
        group: [70],
        birthday: new Date("2002-05-30"),
    },
    {
        name: ["Castle J", "CastleJ"],
        group: [71],
        birthday: new Date("1999-05-31"),
    },
    {
        name: ["BIC"],
        group: [71],
        birthday: new Date("2001-04-25"),
    },
    {
        name: ["Minjae"],
        group: [71],
        birthday: new Date("2003-08-23"),
    },
    {
        name: ["Huijun"],
        group: [71],
        birthday: new Date("2003-10-07"),
    },
    {
        name: ["Win"],
        group: [71],
        birthday: new Date("2004-12-19"),
    },
    {
        name: ["Sunhye"],
        group: [72],
        birthday: new Date("2004-04-12"),
    },
    {
        name: ["Yeonjung"],
        group: [72],
        birthday: new Date("2004-09-01"),
    },
    {
        name: ["Jiana"],
        group: [72],
        birthday: new Date("2006-02-02"),
    },
    {
        name: ["Doeun"],
        group: [72],
        birthday: new Date("2007-12-24"),
    },
    {
        name: ["Jieun"],
        group: [72],
        birthday: new Date("2009-11-05"),
    },
    {
        name: ["Hinata"],
        group: [73],
        birthday: new Date("2004-08-27"),
    },
    {
        name: ["Yuna"],
        group: [73],
        birthday: new Date("2004-03-06"),
    },
    {
        name: ["Rui"],
        group: [73],
        birthday: new Date("2003-11-04"),
    },
    {
        name: ["Jaeyun"],
        group: [74],
        birthday: new Date("2002-07-02"),
    },
    {
        name: ["Myungho"],
        group: [74],
        birthday: new Date("2001-10-12"),
    },
    {
        name: ["Minho"],
        group: [74],
        birthday: new Date("2002-10-14"),
    },
    {
        name: ["Yoonsung"],
        group: [74],
        birthday: new Date("2003-11-13"),
    },
    {
        name: ["Haemin"],
        group: [74],
        birthday: new Date("2004-03-16"),
    },
    {
        name: ["Kyungmin"],
        group: [74],
        birthday: new Date("2004-10-28"),
    },
    {
        name: ["Yungyu"],
        group: [74],
        birthday: new Date("2005-09-07"),
    },
    {
        name: ["Seungheon"],
        group: [74],
        birthday: new Date("2007-05-15"),
    },
    {
        name: ["Taemin"],
        group: [75],
        birthday: new Date("1993-07-18"),
    },
    {
        name: ["Rachel"],
        group: [76],
        birthday: new Date("2000-08-28"),
    },
    {
        name: ["Dalyn"],
        group: [77],
        birthday: new Date("1999-08-27"),
    },
]

//localStorage.removeItem('membersArray');
localStorage.setItem('groupsArray', JSON.stringify(allGroups));
localStorage.setItem('membersArray', JSON.stringify(allMembers));


/*
Daten hinzufügen:
Shinee, April, ANS

komplett hinzufügen:
The Rose, VCHA, NiziU, lovelyz (El7z Up)


Wenn aufgeteilt auf Gruppen und Leute, dann kann man es wie bei CLC Yujin und Iz*One machen, dass mehrere Gruppen drinne sein können,
aber bei den Bildern eben nur die letzten genommen werden, aber bei group guess können alle drinne sein

*/
